<!DOCTYPE html>
<html lang="<!-- locale -->">
<head>
	<title><?= t($this->request->controller); ?> - <?= t($this->request->action); ?> | Fort Ouest <?= t('title'); ?>, Mont-Tremblant, Quebec</title>

    <?= $this->includeFile('layout/meta.phtml'); ?>
    <?= $this->includeFile('layout/assets.phtml'); ?>
</head>
<body>
    <?= $this->includeFile('layout/header-container.phtml'); ?>

    <?= $this->includeFile('layout/nav-container.phtml'); ?>

	<main>
        <?= $this->view->render(); ?>
    </main>

    <?= $this->includeFile('layout/footer-container.phtml'); ?>
</body>
</html>