<section>
    <h1><?= t('prices'); ?></h1>

    <h2><?= t('entries'); ?></h2>
    <table class="table-items">
        <tr>
            <td><?= t('entry'); ?></td>
            <td><?= $this->products->getItemPrice('entry'); ?></td>
        </tr>
        <tr>
            <td><?= t('nightEntry'); ?></td>
            <td><?= $this->products->getItemPrice('entryNight'); ?></td>
        </tr>
    </table>

    <h2><?= t('discounts'); ?></h2>
    <table class="table-items">
        <tr>
            <td>45 - 59 <?= t('people'); ?></td>
            <td>15%</td>
        </tr>
        <tr>
            <td>60 - 74 <?= t('people'); ?></td>
            <td>20%</td>
        </tr>
        <tr>
            <td>75 - 89 <?= t('people'); ?></td>
            <td>25%</td>
        </tr>
        <tr>
            <td>90+ <?= t('people'); ?></td>
            <td>30%</td>
        </tr>
    </table>
</section>




n minimum de 10 joueurs doivent réserver pour qu'on puisse ouvrir un départ.

1) Activité Pogne ou Tague = 24.95$+tx (inclus accès au site, 1h de jeux, équipement de jeux, photos*, animation, assurances et 1 bouteille d'eau.
*Délais de 2 mois & + pour notre sélection de photos gratuites avec votre forfait d'entrée sur notre page Facebook, si le photographe est présent. Vous pouvez recevoir toutes les photos haute résolutions prises par WeTransfert pour
35$+tx ou sur clé USB 3.0 de 16 gigs pour 50$+tx.

2) Heure additionnelle ajouté au forfait d'entrée = 8.95$

3) Pour jeux lors de la pleine lune ou de nuit ajoutez 4.95$ par personne

- - - - - - - - - -

A minimum of 10 players are required to book a group.

1) Grab or Tag Activity = $24.95+tx (includes access to site, 1 hour of game play, game equipment, pictures*, animation, insurance & 1 bottle of water.
*A delay of up to 2 months or more for our selection of free pictures on our Facebook Page offered with your package deal, if the photographer is available. You may get all the pictures in their high resolution format by WeTransfer for only $35+tx or on a 3.0 USB key of 16 gigs for $50+tx.

2) Additional hour of gameplay added to your entry = $8.95+tx

3) For full moon or evening games, add $4.95+tx per player.





À partir de 45 joueurs, à chaque tranche de 15 joueurs, recevez un rabais de 5% sur l'activité et sur les heures additionnelles, jusqu'à un maximum de 40% de rabais.

Exemples :
- 45 joueurs = 15% de rabais = 21.21$ / joueur et 7.61$ pour une heure supplémentaire.
- 90 joueurs = 30% de rabais = 17.47$ / joueur et 6.27$ pour une heure supplémentaire.
- 120 joueurs = 40% de rabais = 14.97$ / joueur et 5.37$ pour une heure supplémentaire. (Rabais maximum = 40%)

- - - - - - - - - -

When booking for 45 players or more, per 15 players booked, you may get a 5% discount on the activity and extra hours of gameplay, all the way up to 40% off our regular prices.

Examples :
- 45 players = 15% discount = $21.21 / player & $7.61 per extra hour of gameplay.
- 90 players = 30% discount = $17.47 / player & $6.27 per extra hour of gameplay.
- 120 players = 40% discount = $14.97 / player & $5.37 per extra hour of gameplay. (max discounts = 40%)