<link rel="shortcut icon" type="image/png" href="/assets/images/favicon.png">

<?php if(false) { ?>
    <link rel="stylesheet" type="text/css" href="/assets/css/main.min.css?v=3">
    <script src="/assets/js/angular.min.js"></script>
    <script async src="/assets/js/main.min.js"></script>
<?php } else { ?>
    <link rel="stylesheet" type="text/css" href="/assets/css/main.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/mobile.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/desktop.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/lib.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/colors.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/sprites.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/content.css">

    <script src="/assets/js/angular.min.js"></script>
    <script async src="/assets/js/lib.js"></script>
    <script async src="/assets/js/main.js"></script>
<?php } ?>