<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="UTF-8">
<meta name="description" content="<?= t('marketing'); ?>">
<meta name="keywords" content="paintball, airsoft, dog sledding, traineau, survival, survie, snowmobile, motoneige, atv, vtt, mont-tremblant, activities">
<meta name="google-site-verification" content="0ygMZau3UuhYW0CEAzUHP6Yl7ExjElZuyhwV9wPyjaE">

<meta property="fb:url"                            		content="http://www.fortouest.com">
<meta property="og:title" 								content="<?= t('title'); ?>">
<meta property="og:description" 						content="<?= t('fortOuestMarketing'); ?>">
<meta property="og:image"              					content="http://www.fortouest.com/assets/images/fbShare.jpg">
<meta property="og:image:type"        					content="image/jpeg">
<meta property="og:image:width"        					content="1200">
<meta property="og:image:height"       					content="630">
<meta property="og:locale" 								content="<?= $this->request->locale; ?>_CA">
<meta property="og:locale:alternate"                    content="<?= $this->request->altLocale; ?>_CA" />
<meta property="og:type" 								content="business.business">
<meta property="business:contact_data:street_address" 	content="<?= $this->contact->address; ?>">
<meta property="business:contact_data:locality"       	content="<?= $this->contact->city; ?>">
<meta property="business:contact_data:postal_code"    	content="<?= $this->contact->postalCode; ?>">
<meta property="business:contact_data:country_name"   	content="<?= $this->contact->country; ?>">
<meta property="place:location:latitude"              	content="46.0146267">
<meta property="place:location:longitude"             	content="-74.5846879">