<?php foreach($this->nav as $r1 => $v1){ ?>
    <li>
        <?php if(!is_array($v1)){ ?>
            <a href="<?= u($r1); ?>"><?= t($v1); ?></a>
        <?php } else {
            $link = '';
            if(isset($v1[$r1])){
                $link = 'href="' . u($v1[$r1]) . '"';
                unset($v1[$r1]);
            }
        ?>
            <a <?= $link; ?> class="desktop"><?= t($r1); ?></a>
            <ul>
                <?php foreach($v1 as $r2 => $v2){ ?>
                    <li>
                        <a href="<?= u($r2); ?>"><?= t($v2); ?></a>
                    </li>
                <?php } ?>
            </ul>
        <?php } ?>
    </li>
<?php } ?>