<section>
	<h1><?= t('paintballInTremblant'); ?></h1>
	<?= $this->includeContent('content/banner.phtml', ['image' => $this->images->paintball]); ?>
	<p><?= t('marketing'); ?></p>
	
	<h2><?= t('rules'); ?></h2>
	<?= $this->includeContent('helper/ul.phtml', ['items' => t('paintballRules')]); ?>
	
	<h2><?= t('whatToBring'); ?></h2>
	<?= $this->includeContent('helper/ul.phtml', ['items' => t('paintballWhatToBring')]); ?>
</section>