<?php 
$route = Request::getRoute();
$locales = ['fr' => 'fr_CA', 'en' => 'en_US'];
$contact = Data_Contact::get('fortOuest');
$title = '';

if($route['controller'] === 'index'){
	$nav1Title = $route['action'];
	$nav2Title = $route['action'];
}
else{
	$nav1Title = $route['controller'];
	$nav2Title = ($route['action'] === 'index') ? 'info' : $route['action'];
	$title = T::get($route['controller']) . ' - ';
}

$nav1Class = (Helper_Nav::hasSecondary() === true) ? 'nav-toggle-half' : 'nav-toggle-full';
$title .= T::get($nav2Title);

if(isset($this->error) === true){
	$title = $this->error;
}

$title .= ' | Fort Ouest ' . T::get('title') . ', Mont-Tremblant, Quebec';
?>
<!DOCTYPE html>
<html lang="<?= $route['locale']; ?>-CA">
<head>
	<title><?= $title; ?></title>

	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8">
	<meta name="description" content="<?= T::get('marketing'); ?>">
	<meta name="keywords" content="paintball, airsoft, dog sledding, traineau, survival, survie, snowmobile, motoneige, atv, vtt, mont-tremblant, activities">
	<meta name="google-site-verification" content="0ygMZau3UuhYW0CEAzUHP6Yl7ExjElZuyhwV9wPyjaE">
	
	<meta property="fb:url"                            		content="http://www.fortouest.com">
	<meta property="og:title" 								content="<?= $title; ?>">
	<meta property="og:description" 						content="<?= T::get('fortOuestMarketing'); ?>">
	<meta property="og:image"              					content="http://www.fortouest.com/public/images/fbShare.jpg">
	<meta property="og:image:type"        					content="image/jpeg">
	<meta property="og:image:width"        					content="1200">
	<meta property="og:image:height"       					content="630">
	<meta property="og:locale" 								content="<?= array_remove($locales, $route['locale']); ?>">
	<meta property="og:locale:alternate" 					content="<?= current($locales); ?>">

	<meta property="og:type" 								content="business.business">
	<meta property="business:contact_data:street_address" 	content="<?= $contact['streetAddress']; ?>">
	<meta property="business:contact_data:locality"       	content="<?= $contact['city']; ?>">
	<meta property="business:contact_data:postal_code"    	content="<?= $contact['postalCode']; ?>">
	<meta property="business:contact_data:country_name"   	content="<?= $contact['country']; ?>">
	<meta property="place:location:latitude"              	content="46.0146267">
	<meta property="place:location:longitude"             	content="-74.5846879">

	<link rel="shortcut icon" type="image/png" href="/public/images/favicon.png">
	<link rel="stylesheet" type="text/css" href="/public/css/main.min.css?v=3">
	<script async src="/public/js/main.min.js"></script>
</head>
<body>
	<header>
		<div class="container">
			<a id="logo" class="lb" href="<?= T::url(['module' => 'index', 'controller' => 'index', 'action' => 'index']); ?>">
				<?= $this->includeContent('html/img', ['group' => 'logos', 'name' => 'fortOuest']); ?>
			</a>
			<div class="rb">
				<a class="icon icon-insta desktop" target="_blank" rel="nofollow" href="<?= $contact['instagram']; ?>">&nbsp;</a>
				<a class="icon icon-fb" target="_blank" rel="nofollow" href="<?= $contact['facebook']; ?>">&nbsp;</a>
				<a class="icon-custom" id="icon-locale" href="<?= T::url(['locale' => key($locales)]); ?>"><?= strtoupper(key($locales)); ?></a>
			</div>
		</div>
	</header>
	<nav>
		<div id="nav1-toggle" class="mobile <?= $nav1Class; ?>"><?= T::get($nav1Title); ?></div
		><?php if($nav1Class === 'nav-toggle-half'){ ?><div id="nav2-toggle" class="mobile nav-toggle-half"><?= T::get($nav2Title); ?></div><?php } ?>

		<ul id="nav1" class="desktop"><?= $this->partial('ui/nav', ['nav' => Helper_Nav::getPrimary()]); ?></ul>
		<ul id="nav2" class="desktop"><?= $this->partial('ui/nav', ['nav' => Helper_Nav::getSecondary()]); ?></ul>
	</nav>
	<main>
		<?= $this->view(); ?>
	</main>
	<footer>
		<div class=" container clearfix">
			<div id="footer-left"><?= $contact['addressLong']; ?></div>
			<div id="footer-right">
				<div><?= $contact['email']; ?></div>
				<div><?= $contact['phone']; ?></div>
				<a class="icon-small icon-insta-small" target="_blank" rel="nofollow" href="<?= $contact['instagram']; ?>">&nbsp;</a>
				<a class="icon-small icon-fb-small" target="_blank" rel="nofollow" href="<?= $contact['facebook']; ?>">&nbsp;</a>
			</div>
		</div>
		<div id="footer-bottom">
			*<?= T::get('taxesNotIncluded'); ?><br/>
			Copyright &copy; <?= date('Y'); ?> Fort Ouest - Alexandre Weihmayer Hamel
		</div>
	</footer>
</body>
</html>