<?php foreach($this->nav as $label => $val){ ?>
	<li>
		<?php if(is_array(current($val)) === false){ ?>
			<a href="<?= T::url($val); ?>"><?= T::get($label); ?></a>
		<?php
		}
		else{
			$link = '';
			
			if(isset($val[$label]) === true){
				$link = 'href="' . T::url($val[$label]) . '"';
				unset($val[$label]);
			}
		?>
			<a <?= $link; ?> class="desktop"><?= T::get($label); ?></a>
			<ul>
			<?php foreach($val as $label2 => $val2){ ?>
				<li>
					<a href="<?= T::url($val2); ?>"><?= T::get($label2); ?></a>
				</li>
			<?php } ?>
			</ul>
		<?php } ?>
	</li>
<?php } ?>