<section>
	<h1><?= t('dogSleddingInTremblant'); ?></h1>
	<?= $this->includeContent('content/banner.phtml', ['image' => $this->images->dogSledding1]); ?>
	
	<p><?= t('missionDesc1'); ?></p>
	<p><?= t('missionDesc2'); ?></p>
	<p><?= t('openingDatesTxt'); ?></p>
	<p><?= t('warnChildrenAndPregnancy'); ?></p>

	<h1><?= t('ourTeam'); ?></h1>

	<h2>Sonia Lanteigne</h2>
	<p><?= t('teamSonia'); ?></p>

	<h2>Maxim Pellerin</h2>
	<p><?= t('teamMax'); ?></p>
</section>